apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongodb
  labels:
    app: mongodb1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb1
  template:
    metadata:
      labels:
        app: mongodb1
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mongodb-secret
              key: mongo-root-password
